server:
  port: 8070
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# 파일 리턴 기본 경로 : src/main/resources/static => 정적인 파일들을 모아두는곳(html, png,jpg…)
# src/main/webapp/WEB-INF/views => 동적인 파일들을 모아두는 곳(jsp) ---- src/main 밑에 webapp/WEB-INF/views 폴더를 생성

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: metacoding
    password: metacoding

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        use-new-id-generator-mappings: false
    show-sql: true
#    properties:
#      hibernate.format_sql: true
      
  jackson:
    serialization:
      fail-on-empty-beans: false

# OAuth 카카오로 통해서 들어오는 user 비밀번호 지정
cos:
  key: cos1234